### ISSUE TITLE
Flutter instructions for running this GitHub Actions

### ISSUE THREAD

**Issue by sebastianbuechler** [emulator-wtf/run-tests#3]
I came across emulator-wtf via this awesome testing suite for flutter: https://patrol.leancode.co/ci/platforms#emulatorwtf Can emulator-wtf also be used with a flutter app (for the android version)? 

If yes, would we just need to build the regular apk with a the flutter/patrol cli and reference the output in the run-tests GitHub Actions? How to build the test apk containing my integration tests with flutter?

**Comment by madisp** [comment]
hey! I don't know too much about the Flutter ecosystem, but I think `patrol build android` should build you both app and test apk files.

And correct, you can then reference these in the `emulator-wtf/run-tests` GitHub Action to run the tests.

**Comment by madisp** [comment]
See the guide here, except for the `gcloud` command you would use the `run-tests` action - https://patrol.leancode.co/ci/firebase-test-lab
